//
//  ProductDetailsConfigurator.swift
//  OnlineCatalogue
//
//  Created by Aleksandr Pronin on 12/6/16.
//  Copyright (c) 2016 Aleksandr Pronin. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension ProductDetailsViewController: ProductDetailsPresenterOutput
{
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    router.passDataToNextScene(segue: segue)
  }
}

extension ProductDetailsInteractor: ProductDetailsViewControllerOutput
{
}

extension ProductDetailsPresenter: ProductDetailsInteractorOutput
{
}

class ProductDetailsConfigurator
{
  // MARK: - Object lifecycle
  
  static let sharedInstance = ProductDetailsConfigurator()
  
  private init() {}
  
  // MARK: - Configuration
  
  func configure(viewController: ProductDetailsViewController)
  {
    let router = ProductDetailsRouter()
    router.viewController = viewController
    
    let presenter = ProductDetailsPresenter()
    presenter.output = viewController
    
    let interactor = ProductDetailsInteractor()
    interactor.output = presenter
    
    viewController.output = interactor
    viewController.router = router
  }
}
