//
//  ProductDetailsPresenter.swift
//  OnlineCatalogue
//
//  Created by Aleksandr Pronin on 12/6/16.
//  Copyright (c) 2016 Aleksandr Pronin. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ProductDetailsPresenterInput
{
  func presentSomething(response: ProductDetails.Something.Response)
}

protocol ProductDetailsPresenterOutput: class
{
  func displaySomething(viewModel: ProductDetails.Something.ViewModel)
}

class ProductDetailsPresenter: ProductDetailsPresenterInput
{
  weak var output: ProductDetailsPresenterOutput!
  
  // MARK: - Presentation logic
  
  func presentSomething(response: ProductDetails.Something.Response)
  {
    // NOTE: Format the response from the Interactor and pass the result back to the View Controller
    
    let viewModel = ProductDetails.Something.ViewModel()
    output.displaySomething(viewModel: viewModel)
  }
}
