//
//  ProductDetailsModels.swift
//  OnlineCatalogue
//
//  Created by Aleksandr Pronin on 12/6/16.
//  Copyright (c) 2016 Aleksandr Pronin. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

struct ProductDetails
{
  struct GetProduct
  {
    struct Request
    {
    }
    struct Response
    {
        var product: Product
    }
    struct ViewModel
    {
        struct DisplayedProduct
        {
            var id: String
            var title: String
            var price: String
            var pictureURLString: String?
        }
        var displayedProduct: DisplayedProduct
    }
  }
}
