//
//  ProductDetailsInteractor.swift
//  OnlineCatalogue
//
//  Created by Aleksandr Pronin on 12/6/16.
//  Copyright (c) 2016 Aleksandr Pronin. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ProductDetailsInteractorInput
{
    func getProduct(_ request: ProductDetails.GetProduct.Request)
    var product: Product! { get set }
}

protocol ProductDetailsInteractorOutput
{
    func presentProduct(_ response: ProductDetails.GetProduct.Response)
}

class ProductDetailsInteractor: ProductDetailsInteractorInput
{
    var output: ProductDetailsInteractorOutput!
    var worker: ProductDetailsWorker!
    var product: Product!
    
    // MARK: - Business logic
    
    func getProduct(_ request: ProductDetails.GetProduct.Request)
    {
        // NOTE: Create some Worker to do the work
        
        worker = ProductDetailsWorker()
        worker.doSomeWork()
        
        // NOTE: Pass the result to the Presenter
        
        let response = ProductDetails.GetProduct.Response(product: product)
        output.presentProduct(response)
    }
}
