//
//  ProductDetailsInteractor.swift
//  OnlineCatalogue
//
//  Created by Aleksandr Pronin on 12/6/16.
//  Copyright (c) 2016 Aleksandr Pronin. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ProductDetailsInteractorInput
{
  func doSomething(request: ProductDetails.Something.Request)
}

protocol ProductDetailsInteractorOutput
{
  func presentSomething(response: ProductDetails.Something.Response)
}

class ProductDetailsInteractor: ProductDetailsInteractorInput
{
  var output: ProductDetailsInteractorOutput!
  var worker: ProductDetailsWorker!
  
  // MARK: - Business logic
  
  func doSomething(request: ProductDetails.Something.Request)
  {
    // NOTE: Create some Worker to do the work
    
    worker = ProductDetailsWorker()
    worker.doSomeWork()
    
    // NOTE: Pass the result to the Presenter
    
    let response = ProductDetails.Something.Response()
    output.presentSomething(response: response)
  }
}
