//
//  ProductsListInteractor.swift
//  OnlineCatalogue
//
//  Created by Aleksandr Pronin on 12/6/16.
//  Copyright (c) 2016 Aleksandr Pronin. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ProductsListInteractorInput
{
    func fetchStoredProducts(request: ProductsList.FetchStoredProducts.Request)
}

protocol ProductsListInteractorOutput
{
    func presentStoredProducts(response: ProductsList.FetchStoredProducts.Response)
}

class ProductsListInteractor: ProductsListInteractorInput
{
    var output: ProductsListInteractorOutput!
    var productsWorker = ProductsWorker(productsStore: ProductsMemStore())
    
    // MARK: - Business logic
    
    func fetchStoredProducts(request: ProductsList.FetchStoredProducts.Request)
    {
        productsWorker.fetchStoredProducts { (products) -> Void in
            let response = ProductsList.FetchStoredProducts.Response(products: products)
            self.output.presentStoredProducts(response: response)
        }
    }
}
