//
//  ProductsListModels.swift
//  OnlineCatalogue
//
//  Created by Aleksandr Pronin on 12/6/16.
//  Copyright (c) 2016 Aleksandr Pronin. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

struct ProductsList
{
    struct FetchStoredProducts
    {
        struct Request
        {
        }
        struct Response
        {
            var products: [Product]
        }
        struct ViewModel
        {
            struct DispayedProduct
            {
                var id: String
                var site_id: String
                var title: String
                var price: String
                var currency_id: String
                var thumbnailURLString: String
            }
            var displayedProducts: [DispayedProduct]
        }
    }
}
