//
//  ProductsListPresenter.swift
//  OnlineCatalogue
//
//  Created by Aleksandr Pronin on 12/6/16.
//  Copyright (c) 2016 Aleksandr Pronin. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ProductsListPresenterInput
{
  func presentSomething(response: ProductsList.Something.Response)
}

protocol ProductsListPresenterOutput: class
{
  func displaySomething(viewModel: ProductsList.Something.ViewModel)
}

class ProductsListPresenter: ProductsListPresenterInput
{
  weak var output: ProductsListPresenterOutput!
  
  // MARK: - Presentation logic
  
  func presentSomething(response: ProductsList.Something.Response)
  {
    // NOTE: Format the response from the Interactor and pass the result back to the View Controller
    
    let viewModel = ProductsList.Something.ViewModel()
    output.displaySomething(viewModel: viewModel)
  }
}
