//
//  ProductsListConfigurator.swift
//  OnlineCatalogue
//
//  Created by Aleksandr Pronin on 12/6/16.
//  Copyright (c) 2016 Aleksandr Pronin. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension ProductsListViewController: ProductsListPresenterOutput
{
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    router.passDataToNextScene(segue: segue)
  }
}

extension ProductsListInteractor: ProductsListViewControllerOutput
{
}

extension ProductsListPresenter: ProductsListInteractorOutput
{
}

class ProductsListConfigurator
{
  // MARK: - Object lifecycle
  
  static let sharedInstance = ProductsListConfigurator()
  
  private init() {}
  
  // MARK: - Configuration
  
  func configure(viewController: ProductsListViewController)
  {
    let router = ProductsListRouter()
    router.viewController = viewController
    
    let presenter = ProductsListPresenter()
    presenter.output = viewController
    
    let interactor = ProductsListInteractor()
    interactor.output = presenter
    
    viewController.output = interactor
    viewController.router = router
  }
}
