//
//  ProductsWorker.swift
//  OnlineCatalogue
//
//  Created by Aleksandr Pronin on 12/6/16.
//  Copyright (c) 2016 Aleksandr Pronin. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import Foundation

// MARK: - Products worker

class ProductsWorker
{
    var productsStore: ProductsStoreProtocol
    
    init(productsStore: ProductsStoreProtocol) {
        self.productsStore = productsStore
    }
    
    func fetchStoredProducts(_ completionHandler: @escaping (_ products: [Product]) -> Void)
    {
        productsStore.fetchStoredProducts { (products: [Product]) -> Void in
            completionHandler(products)
        }
    }
}

// MARK: - Products store API

protocol ProductsStoreProtocol {
    func fetchStoredProducts(_ completionHandler: @escaping (_ products: [Product]) -> Void)
}
